### ISSUE TITLE
Can you share cifar noise file

### ISSUE THREAD

**Issue by ShiningSord** [LiJunnan1992/DivideMix#10]
Hello, I have repeated experiments on cifar10 and cifar100, and I find that accuracy is affected by noise file when noise ratio is high(0.8/0.9). I got only 54.6/27.9 on cifar100 with 0.8/0.9 noise ratio, which are much lower than that claimed in paper(60.2/31.5). 

so, can you share the noise file?
Thanks:)

**Comment by LiJunnan1992** [comment]
Hi, thanks for trying out our code!
Have you adjusted the hyper-parameters for high noise ratio? According to our paper, lambda_u=150, and p_threshold=0.6 for 90% noise.

**Comment by ShiningSord** [comment]
Thanks for your reply!
i retried cifar100 with 0.8/0.9 noise ratio, and my hyper-parameters are lambda_u=150, p_threshold=0.5/0.6. the best accuracy on test set are 57.63/30.5. Are there more hyper-parameters should be adjusted?

**Comment by ShiningSord** [comment]
I made a mistake on the setting of batchsize. After I correct it, the result is just same as that claimed in paper! 
Thanks for your nice work, and I will close this issue.
