### ISSUE TITLE
Can you share how you organized clothing1m dataset?

### ISSUE THREAD

**Issue by wjun0830** [LiJunnan1992/DivideMix#12]
I have downloaded clothing1m dataset.
The Dataset I downloaded has architecture
```
.
├─clean_test
├─clean_train
├─clean_valid
├─noisy_train
```
which contains only jpg not txt files such as noisy_label_kv.txt

Can you share these files necessary for running the code?

**Comment by LiJunnan1992** [comment]
There should be an annotation.zip file. Can I have your email so I can share it with you?

**Comment by wjun0830** [comment]
> There should be an annotation.zip file. Can I have your email so I can share it with you?

Thank you. My email address is wjun0830@gmail.com

**Comment by sailist** [comment]
Could you please share it with me? I have no annotation.zip file in the dataset, My email is sailist@outlook.com, Thank you!

**Comment by rayleizhu** [comment]
> There should be an annotation.zip file. Can I have your email so I can share it with you?

@LiJunnan1992 @sailist  @wjun0830

 Can you also send me one copy?  rayleizhu2019@gmail.com

Thanks.

**Comment by LiJunnan1992** [comment]
Sent! @rayleizhu

**Comment by LiJunnan1992** [comment]
> Could you please share it with me? I have no annotation.zip file in the dataset, My email is [sailist@outlook.com](mailto:sailist@outlook.com), Thank you!

sent! @sailist

**Comment by Gxinhu** [comment]
Could you please also send it to me? My email is laohuxin@gmail.com

> There should be an annotation.zip file. Can I have your email so I can share it with you?

**Comment by spongiaaa** [comment]
Appreciate for your great work! Could you please send me a copy of annotation.zip file? My email is spongiaaa@126.com. Thank you very much!
btw this is my first time to try to reproduce a paper><

**Comment by wwl1999** [comment]
Could you please share it with me? I have no annotation.zip file in the dataset, My email is wangwei19991112@163.com, Thank you! @LiJunnan1992 @wjun0830 @rayleizhu @sailist

**Comment by sailist** [comment]
链接：https://pan.baidu.com/s/1CXg2i7P_MY1njodDN6X7Nw 
提取码：s4nx
