### ISSUE TITLE
some question about when noise_mode = asym

### ISSUE THREAD

**Issue by Wongcheukwai** [LiJunnan1992/DivideMix#13]
Hi Junnan,

I really like your paper and am running your code. But I have some question regarding how you deal with asymmetric noise.

1. In line 24 in dataloader_cifar.py, did you just match similar class manually? Because I checked the Cifar official website, it seems you just match similar classes like cats and dogs, deers and horses, birds and planes. May I ask why you generate asymmetric data like this?

2. I didn't find  the asymmetric class transition for Cifar100 in your code and it is interesting that you didn't report asymmetric noise accuracy in you paper in Table 5. So can you tell me how you generate asymmetric data for Cifar100?

Looking forward to your reply!

**Comment by LiJunnan1992** [comment]
Hi,
1. Yes for asymmetric noise only visually similar class labels are exchanged. The similar classes were defined by previous papers and I followed their definition. 
2. I didn't generate asymmetric noise for cifar100. As far as I know, there hasn't been a commonly-followed definition of what classes are visually similar for cifar100.

**Comment by Wongcheukwai** [comment]
thank you for your reply.
As in previous paper, do you mean Unsupervised label noise modelling and loss correction?

**Comment by LiJunnan1992** [comment]
The F-correction, Joint-Optim, Meta-Learning, and P-correction paper use the same asymmetric noise.

**Comment by Wongcheukwai** [comment]
thanks Junnan I will close this one. Just wanted to say your paper inspired me a lot.
