### ISSUE TITLE
Can you share log file of training cifar10 of asym noise?

### ISSUE THREAD

**Issue by wjun0830** [LiJunnan1992/DivideMix#15]
Hi Junnan. I really appreciate your work and it helps me study a lot actually.

However, somehow, I cannot get the result as same as you mentioned in your paper.
It shows that asym 40% noise on cifar-10 should give 93% accuracy but what i see is middle of 80s.

Can you share your log file of asym0.4-cifar10?
![image](https://user-images.githubusercontent.com/31557552/89376586-0bd07d80-d72b-11ea-85c2-c6780cd504e3.png)

This is image of middle of the process.

**Comment by LiJunnan1992** [comment]
Hi, thanks for trying our code! 
For asym noise, you need to set lambda_u = 0, as shown in our paper's appendix. Also, you need to finish 300 epochs to get the reported performance.

**Comment by wjun0830** [comment]
Oh i missed that. Thanks

**Comment by MrChenFeng** [comment]
Hi Junnan, could you explain a bit why unlabeled part loss should be avoid in asym noise mode? Thanks so much!

**Comment by LiJunnan1992** [comment]
Hi,
the labeled loss already contain information for the unlabeled samples because of mixup, and we found the extra regularization of the unlabeled loss to be not necessary.
