### ISSUE TITLE
Re-implementation of your result about P-correct

### ISSUE THREAD

**Issue by congyang1996** [LiJunnan1992/DivideMix#16]
Hi Junnan, so nice of your work! 
In your paper, you cited this work, P-correction (Yi & Wu, 2019) , and re-implemented this work, get worse result than his paper. I have done the same thing, and get even worse result than your re-implementation. 
Could you please share some experience in re-implementation? Thank you a lot! ^_^

**Comment by LiJunnan1992** [comment]
Hi thanks for asking!
I mostly follow their paper for the re-implementation, but I do observe that training could sometimes be a bit unstable. It is probably better that you check with the authors for their paper :)
