### ISSUE TITLE
Ask for hyperparameter for Table 6

### ISSUE THREAD

**Issue by ShiningSord** [LiJunnan1992/DivideMix#19]
Hello, thanks for your excellent work!
I'm trying to reproduce your experiments in Table 6. And I noticed that hyperparameters(e.g., lambda_u, threshold tau) are not mentioned in the original paper. Can you share the hyperparameter For Table 6?

**Comment by LiJunnan1992** [comment]
Hi, thanks for your interest in our work!
Table 6 uses the same set of hyper-parameters as Table 1.  80% noise in Table 6 is similar to 90% noise in Table 1.

**Comment by ShiningSord** [comment]
Thanks, that is what i need.
