### ISSUE TITLE
Data set used for module 'dataloader_cifar'

### ISSUE THREAD

**Issue by FFANGTE** [LiJunnan1992/DivideMix#21]
Hi. Thanks for your exciting paper to me!
I'd like to implement on your code but there is no dataset used in the module 'dataloader_cifar'.
When 'unpickle' the file, there is no data dict file so arise error.
I think the cifar dataset which used in this code will have some proper form like 'dictionary'.
Where could i get this dataset?

**Comment by FFANGTE** [comment]
I did by using dataset from the github of the paper 'Co-teaching'.
But i want to know where can i get this.

**Comment by LiJunnan1992** [comment]
Hi, you can download the cifar dataset from the official website: https://www.cs.toronto.edu/~kriz/cifar.html. Thanks!
