### ISSUE TITLE
Your new paper: "Towards Noise-resistant Object Detection with Noisy Annotations"

### ISSUE THREAD

**Issue by edwardnguyen1705** [LiJunnan1992/DivideMix#24]
Dear @LiJunnan1992 ,

I am very interested in your research, especially your new [paper](https://arxiv.org/abs/2003.01285) . Are you going to release its source code so that we can reproduce the results?

**Comment by LiJunnan1992** [comment]
Hi, thanks for your interest! We will release code for that paper upon acceptance.

**Comment by edwardnguyen1705** [comment]
Thanks for your time.

**Comment by ciroimmobile** [comment]
Dear @LiJunnan1992 ,

I am very interested in your research, especially your new [paper](https://arxiv.org/abs/2003.01285) . Are you going to release its source code so that we can reproduce the results?
