### ISSUE TITLE
About the accuracy of the asym noise in cifar10

### ISSUE THREAD

**Issue by Midkey** [LiJunnan1992/DivideMix#26]
Hello, thanks for your nice work!
I run the Train_cifar.py code, and set the **noise_mode** to **asym**, the **r**( noise rate) to 0.4  .
Then I found the highest accuracy is 83.+ , differing from your paper mentioned about 92.1/93.4.
Am I make some mistake or need to change some hyperparameter?
Thank~

....
Epoch:280   Accuracy:81.89
Epoch:281   Accuracy:81.77
Epoch:282   Accuracy:82.54
Epoch:283   Accuracy:82.56
Epoch:284   Accuracy:82.96
Epoch:285   Accuracy:82.65
Epoch:286   Accuracy:82.90
Epoch:287   Accuracy:82.20
Epoch:288   Accuracy:82.63
Epoch:289   Accuracy:82.06
Epoch:290   Accuracy:82.03
Epoch:291   Accuracy:82.68
Epoch:292   Accuracy:82.34
Epoch:293   Accuracy:82.37
Epoch:294   Accuracy:83.15
Epoch:295   Accuracy:82.32
Epoch:296   Accuracy:82.14
Epoch:297   Accuracy:82.18
Epoch:298   Accuracy:82.28
Epoch:299   Accuracy:82.63
Epoch:300   Accuracy:82.62

**Comment by LiJunnan1992** [comment]
Hi, thanks for your interest!

As shown in our paper's appendix, for asym noise, lambda_u = 0.
