### ISSUE TITLE
A question about the paper

### ISSUE THREAD

**Issue by mxzel** [LiJunnan1992/DivideMix#28]
I noticed that you have made a comparison with Joint-opt under the asym setting, but there is no comparison with it under the sym setting. Why?

**Comment by LiJunnan1992** [comment]
Hi, the result reported in Joint-opt for sym does not follow the same setting as ours. Furthermore, Joint-opt is not the best baselines. Hence we only include the asym setting. Thanks.

**Comment by mxzel** [comment]
Got it. Thanks.
