### ISSUE TITLE
Some questions in Figure 2

### ISSUE THREAD

**Issue by RumengYi** [LiJunnan1992/DivideMix#3]
hello，I'm repeating your work, and can you explain how the pdf corresponding to each loss in figure 2 was drawn, and which function in GMM was used?

**Comment by LiJunnan1992** [comment]
Hi, figure 2 was drawn by plotting the histogram of per-sample losses.

**Comment by ghost** [comment]
Hi, thanks very much for such an excellent work! 
I feel very curiosity that why you not plot the distribution of the probability that given by GMM, as in the following stages (i.e., co-guessing, co-refinement), the split of the data-set is mainly based on that.
Is there any difference?

**Comment by LiJunnan1992** [comment]
Hi, the split of the dataset is at the start of each epoch, where we forward-pass all samples and use GMM on the per-sample losses.
