### ISSUE TITLE
Could you share the Clothing-1M dataset?

### ISSUE THREAD

**Issue by FFANGTE** [LiJunnan1992/DivideMix#30]
I did my best but i couldn't find where can i get the dataset.
Would you share the dataset you had downloaded?
Or please tell me the website to get the dataset.

**Comment by LiJunnan1992** [comment]
Hi, I emailed the authors of Clothing1M to get the dataset

**Comment by FFANGTE** [comment]
Sorry but i did that and i got!
Thank you :)

**Comment by TqXue** [comment]
> 

Hi，could you please share the dataset Clothing1M with me? I want it, too. Thanks a lot!!
