### ISSUE TITLE
Question about the clothing1M dataset.

### ISSUE THREAD

**Issue by chenmc1996** [LiJunnan1992/DivideMix#34]
I notice that there is a clean training set in the clothing1M (clean_train_key_list.txt). It seems consist of images different from the noisy training set. 
Does dividemix use it?  Or is it common pratice to ignore it in the field of LNL?

**Comment by LiJunnan1992** [comment]
DivideMix does not use it. A few other LNL works have used it.

**Comment by chenmc1996** [comment]
Thanks.
