### ISSUE TITLE
When r=0.1， the accuracy is 87.89.

### ISSUE THREAD

**Issue by jiangwenj02** [LiJunnan1992/DivideMix#35]
Thank you for your code,. However i meet some problems. When i adjust the r to 0.1， the accuracy is only 87.89.  which parametes need to adjust?

**Comment by LiJunnan1992** [comment]
Following Table 7 in the paper, you can try to adjust lambda_u to 0.

**Comment by jiangwenj02** [comment]
Thank you

Junnan Li ***@***.***> 于2021年12月17日周五 07:52写道：
