### ISSUE TITLE
about number of data augmentations?

### ISSUE THREAD

**Issue by abcde-1447** [LiJunnan1992/DivideMix#36]
Hi, thanks for sharing this repo!

I have been reading your code together with your paper, and noticed that in your paper you mentioned to run M data augmentations for unlabeled data, while in https://github.com/LiJunnan1992/DivideMix/blob/d9d3058fa69a952463b896f84730378cdee6ec39/dataloader_cifar.py#L113-L114, there are 2 transformations, I am wondering if you have fixed M=2 here, or did I misunderstand something?

BTW, do you think this method is applicable to regression problem as well?

Thank you!

**Comment by LiJunnan1992** [comment]
Hi, as mentioned in the paper, we set M=2.
I think it should be applicable to regression problem, but may require some modification depending on the task.

Thanks!

**Comment by abcde-1447** [comment]
Thanks for the explanation!
