### ISSUE TITLE
the webvision dataset is Resized version or Full resolution version?

### ISSUE THREAD

**Issue by wangzhenzhou2020** [LiJunnan1992/DivideMix#37]
Hi Junnan，

I have a question about the webvision dataset :
The webvision dataset has two versions, Resized and or Full resolution.
 Which version of webvision dataset is selected in the paper？

Best Regards,
Zhenzhou

**Comment by LiJunnan1992** [comment]
Hi,
The paper used the resized version.

Thanks,
Junnan
