### ISSUE TITLE
ImageNet val 50 classes

### ISSUE THREAD

**Issue by Pexure** [LiJunnan1992/DivideMix#38]
Dear Junnan,
I'm from NUS SoC and I want to follow this work. Can you provide `synsets.txt` for selection of ImageNet val 50 classes (as I saw in another issue)? Or can you provide a snippet to choose them? I'd appreciate that very much.

**Comment by LiJunnan1992** [comment]
Hi,
You should be able to find it from webvision dataset: https://data.vision.ee.ethz.ch/cvl/webvision/download.html
just download "Training & Validation Labels (183 MB)"

**Comment by Pexure** [comment]
Thanks.
