### ISSUE TITLE
How to specify gpu

### ISSUE THREAD

**Issue by kai-wen-yang** [LiJunnan1992/DivideMix#43]
I have 4 gpu on my machine, and I want to run your code on gpu 1, my command is:
```
python train_cifar.py --gpu_ids 1
```
But it raises issue:
```
model = model.to(device)
    RuntimeError: CUDA error: invalid device ordinal
```

My gpu is normal. Do you have any idea?

**Comment by LiJunnan1992** [comment]
The argument is gpuid, singular form.
