### ISSUE TITLE
Effectiveness of the mixup operation

### ISSUE THREAD

**Issue by hathawayxxh** [LiJunnan1992/DivideMix#45]
Hi Junnan,

Thanks for your excellent work and codes. In the ablation study (Table 5) of your paper, you have conducted the experiments of "DivideMix w/o augmentation". I would like to know what does the augmentation refers to? Does it means the M transformations or the mixup operation? If this augmentation denotes the M transformations, have you ever evaluated the impact of the mixup operation?

Thanks a lot.
Xiaohan

**Comment by LiJunnan1992** [comment]
Hi Xiaohan, thanks for your question.

The augmentation in Table 5 refers to M transformations. I have not removed mixup because it is an essential piece of the mixmatch operation.

**Comment by hathawayxxh** [comment]
Thanks for your reply. I will close this issue.
