### ISSUE TITLE
Evaluation 50 classes WebVision

### ISSUE THREAD

**Issue by DiegoOrtego** [LiJunnan1992/DivideMix#6]
Hi,

Many thanks for sharing the code of your cool work!

I am trying to evaluate your approach in the ImageNet val set when training with first 50 classes of WebVision. I wonder how do you get the right 50 classes from ImageNet to map the first 50 classes of WebVision.

**Comment by LiJunnan1992** [comment]
Hi,

You can find the class sequence numbers (e.g. n01440764) in "synsets.txt" provided by webvision dataset, and use that to find corresponding imagenet classes.

**Comment by DiegoOrtego** [comment]
Cheers! All I needed!
Btw, I am glad that our work (Unsupervised Label Noise Modeling and Loss Correction) inspired yours to drive our mixture modelling idea forward! Really cool a dynamic semi-supervised learning recomputing the clean subset based on label noise modelling with cross-network models ;)

**Comment by LiJunnan1992** [comment]
Thanks! Your work was a big inspiration!
